all:
	@echo "building all"
	go build main.go gossip.go blockchain.go myTypes.go utils.go logging.go

clean:
	@echo "deleting binaries"
	rm main launcher 

launcher:
	@echo "deleting binaries"
	go build launcher.go
